[package]
name = "poseidon_swap"
version = "1.0.0"
authors = []

[addresses]
std = "0x1"
poseidon_swap = "_"  # This will be replaced with your deployment address
umi_token = "_"
shell_token = "_"

[dev-addresses]

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-framework.git", rev = "aptos-release-v1.27", subdir = "aptos-framework" }

[dev-dependencies]
